name: Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Generate definitions
    strategy:
      matrix:
        ref:
          - develop
          - '50\.'
          - '0\.47\.'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Fetch DFHack repo history
        run: git fetch --unshallow
        working-directory: dfhack

      - name: Checkout DFHack ref
        id: checkout-ref
        run: |
          git log --format='short'
          git checkout $(git log --pretty='format:%H %d' | grep -E '${{ matrix.ref }}' | head -n 1 | awk '{print $1}')
          echo "name=$(git describe --tags --exact-match 2>/dev/null || echo 'develop')" > $GITHUB_OUTPUT
        working-directory: dfhack

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate definitions
        run: bundle exec rake build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dfhack-lua-definitions-${{ steps.checkout-ref.outputs.name }}
          path: dist
