name: Build nightly release

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update_submodules:
    uses: ./.github/workflows/update-submodules.yml
    permissions:
      contents: write
    
  update_definitions:
    uses: ./.github/workflows/update-definitions.yml
    permissions:
      contents: write

  build:
    uses: ./.github/workflows/build.yml
