name: release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Package library
        run: |
          tar -zcf dfhack-lua-definitions-$(git tag --points-at HEAD).tar.gz dist
          zip -9qr dfhack-lua-definitions-$(git tag --points-at HEAD).zip dist
      - name: Create a new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $(git tag --points-at HEAD) dfhack-lua-definitions-$(git tag --points-at HEAD).*
