name: Release
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4

      - name: Package artifacts
        run: |
          for artifact in dfhack-lua-definitions-*
          do
            tar -zcf ${artifact}.tar.gz $artifact
            zip -9qr ${artifact}.zip $artifact
          done

      - name: Create a new release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create $(git tag --points-at HEAD) dfhack-lua-definitions-*.zip dfhack-lua-definitions-*.tar.gz
