name: Update definitions

on: workflow_call

jobs:
  run:
    name: Update definitions
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Generate definitions
        run: rake build

      - name: Check if definitions changed
        id: definitions_changed
        run: echo "changed=$(git diff --quiet HEAD -- dist; echo $?)" >> $GITHUB_OUTPUT

      - name: Setup git user
        if: ${{ steps.definitions_changed.outputs.changed == true }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit changes
        if: ${{ steps.definitions_changed.outputs.changed == true }}
        run: |
          git add dist
          git commit -m "Auto-update definitions"
          git push
