name: update
run-name: Update library files

# TODO: Figure out a release workflow.
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rake
        continue-on-error: true
      - run: bundle exec rake build
      - name: Check for changes
        id: dist_updated
        run: git diff --quiet HEAD -- dist
      - name: Setup git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Push changes
        if: ${{ steps.dist_updated.outcome == 'failure' }}
        run: |
          git add dist
          git commit -m "Update library files"
          git push
