name: Update submodules

on: workflow_call

jobs:
  run:
    name: Update submodules
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          # Cannot use the commit SHA because there may have been updates.
          ref: ${{ github.ref }}
          submodules: true

      - name: Update submodules
        run: git submodule update --remote

      - name: Check if submodules updated
        id: submodules_updated
        run: echo "changed=$(git diff --quiet HEAD -- dfhack; echo $?)" >> $GITHUB_OUTPUT

      - name: Setup git user
        if: ${{ steps.submodules_updated.outputs.changed == true }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit changes
        if: ${{ steps.submodules_updated.outputs.changed == true }}
        run: |
          git add dfhack
          git commit -m "Auto-update submodules"
          git push
